env:
  browser: true
  node: true
  es6: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:react/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:@next/next/recommended
  - prettier

plugins:
  - "@typescript-eslint"
  - react
  - react-hooks
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  project:
    - "./tsconfig.json"
settings:
  react:
    version: detect
  next:
    rootDir: "packages/site"

rules:
  no-console: off
  "@typescript-eslint/no-unsafe-assignment": off
  "@typescript-eslint/unbound-method": off
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  react/display-name: off
  react/prop-types: off

  import/order:
    - error
    - alphabetize:
        order: asc
      newlines-between: always

ignorePatterns:
  - "**/dist/*"
  - "**/lib/*"
  - "**/esm/*"
  - "**/cjs/*"
  - "**/pkg/*"
  - "**/*.config.js"
