[package]
name = "sim"
version = "0.1.0"
authors = ["まどの <madonoharu@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = { version = "0.2.69", features = ["serde-serialize"] }
js-sys = "0.3.46"
serde_derive = "1.0.120"
serde = { version = "1.0.120", features = ["derive"] }
serde_json = "1.0.61"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }
strum = "0.20.0"
strum_macros = "0.20.1"
num-traits = "0.2.14"
num-derive = "0.3.3"
num_enum = "0.5.1"
fasteval = "0.2.4"
paste = "1.0.4"
arrayvec = { version = "0.5.2", features = ["serde"] }
wasmer_enumset = "1.0.1"

[dependencies.web-sys]
version = "0.3.46"
features = [
  "console"
]

[dev-dependencies]
wasm-bindgen-test = "0.3.19"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]