[package]
name = "ts-gen"
version = "0.1.0"
edition = "2018"

[dependencies]
fh-core = { path = "../../core" }

[dependencies.ts-rs]
git = "https://github.com/arendjr/ts-rs"
rev = "945b336e26bef0bfeba74f4d26768fede91f57f5"