name: API
on:
  workflow_dispatch:
    inputs:
      NAME:
        required: true
        type: string
      ID_TOKEN:
        type: string

permissions:
  contents: read

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install dependencies
        uses: ./.github/actions/bun-install

      - name: Cache Rust builds
        uses: Swatinem/rust-cache@v2

      - name: Build workspace dependencies
        run: bun run setup

      - run: bun run dispatch
        env:
          NAME: ${{ github.event.inputs.NAME }}
          ID_TOKEN: ${{ github.event.inputs.ID_TOKEN }}
          SERVICE_ACCOUNT_CLIENT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_CLIENT_EMAIL }}
          SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
