name: update-master-data
on:
  repository_dispatch:
    types: [update-master-data]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Checkout
        uses: actions/checkout@v2

      - run: yarn --frozen-lockfile
      - run: yarn update-master-data
        env:
          SERVICE_ACCOUNT_CLIENT_EMAIL: ${{ secrets.SERVICE_ACCOUNT_CLIENT_EMAIL }}
          SERVICE_ACCOUNT_PRIVATE_KEY: ${{ secrets.SERVICE_ACCOUNT_PRIVATE_KEY }}
