name: update-storage
on: repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: yarn --frozen-lockfile
      - run: yarn ts-node scripts/updateMasterData
