name: update-master-data
on: repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - run: yarn --frozen-lockfile
      - run: yarn update-master-data
